### ISSUE TITLE
Catching your local branch up to speed

### ISSUE THREAD

**Issue by GeorgeJJW** [UBC-MDS/picfixPy#18]
We are starting to implement and merging more and more features into the remote `master` on github.

Here is a quick reference on how to update your local branch (such as the `sharpen` branch on your computer) such that your local work is not falling too far behind. 

[at the root of your local clone of this repo]

1. Not a bad idea to always check the local branch that you are currently in.
 `git branch` 

2. If you are in your local feature branch, such as `contrast` or `sharpen`, great! Now you can switch to your local `master`, and catch your local `master` up to speed with the remote `master`.
`git checkout master`
`git pull` 

3. You can now switch back to your local feature branch (`sharpen` or `vibrance`, etc), and incorporate changes from the local master to your local feature branch.
`git checkout sharpen` or `git checkout vibrance`
`git merge master`

4. Resolve any merge conflicts locally, and your local branch should now be all up-to-date with the remote `master`!

5. Continue working on your function and test in your local branch (use `git branch` when in doubt!), and make commits as usual. When you are ready, push your work from your local feature branch to your remote feature branch by simply using:
`git push` 
(We are allowed to do this now because the first time you pushed to your remote feature branch you should be using `git push -u origin vibrance` or `git push -u origin sharpen`, so now you can simply use `git push` to do the same.)

6. Make a pull request to merge your remote feature branch to the remote `master` on github.

A summary of the above commands:
```
git checkout master
git pull
git checkout sharpen (or vibrance)
git merge master
[continue working on your function and tests]
git push
[issue a pull request on github when ready]
```

There are faster and more hacky ways of doing this, but I think it will be nice for us to practice what git is actually doing :grinning: .

**Comment by mkeyim** [comment]
Thanks for this George!
