### ISSUE TITLE
Limiting image inputs and outputs 

### ISSUE THREAD

**Issue by mkeyim** [UBC-MDS/picfixPy#19]
We should not limit our functions in python to just .png in the documentation, when our function works for many other formats (jpg, jpeg, pdf, png, both input and output wise - it can save pdfs! Ive tried!), this is doing our package a disservice in Python.
We can limit in R because of R's limitations, but I really do not think we should limit in python as python is a language that's USED for its flexibility and ease. Thoughts?

**Comment by mkeyim** [comment]
I would like to update our function documentation if we all agree to include all the other formats our functions can handle.

**Comment by GeorgeJJW** [comment]
I agree, we can do a python specific documentation, detailing the known image types that we can support. We can finalize the documentation once we've seen @ksm45's implementation of #12.

**Comment by GeorgeJJW** [comment]
This issue will be addressed in #21, closing this for now.
