### ISSUE TITLE
Milestone 02 feedback

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/picfixPy#28]
Hello,

- The package setup and tests run without any problems
- I see that you are on track and did most of the required tasks in Milestone 02.
- You have efficiently used github workflow efficiently including  issue tracker, commits..., but I see you didn't create branches and pull requests.
- Your function documentation is complete for both README and functions. 

Thanks!

**Comment by GeorgeJJW** [comment]
Hello @hsmohammed,

Thank you for the timely feedback.

I want to add that we did make extensive use of branching and pull requests, we followed Varada's instructions to _delete_ the branches after they have been merged. 

As can be seen here from pull request #22, for instance.

![image](https://user-images.githubusercontent.com/3982153/53367115-63de4000-38fa-11e9-94f6-9e981f027aeb.png)

All the closed pull request can be found [here](https://github.com/UBC-MDS/picfixPy/pulls?q=is%3Apr+is%3Aclosed)

**Comment by GeorgeJJW** [comment]
Here is a reference to Varada's instruction:

![image](https://user-images.githubusercontent.com/3982153/53367288-96883880-38fa-11e9-8daa-f7a1c6c92209.png)

**Comment by hsmohammed** [comment]
Hi George,

Thanks for the clarification. I will modify your grades accordingly.

Thanks!
